/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package rmpspos_productdata;

import java.awt.Dimension;
import java.awt.GraphicsEnvironment;
import java.awt.Rectangle;
import java.awt.Toolkit;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import static rmpspos_productdata.RMPSPOS_Home.SavingChangesToFile;
import static rmpspos_productdata.RMPSPOS_Home.products;

/**
 *
 * @author lance
 */
public class Edit extends javax.swing.JPanel {
    
    static Dimension scrnSize = Toolkit.getDefaultToolkit().getScreenSize();
    static Rectangle winSize = GraphicsEnvironment.getLocalGraphicsEnvironment().getMaximumWindowBounds();
    static int taskBarHeight = scrnSize.height - winSize.height;
    static String oldDesc = "";
    static float oldCost = 0;
    static float oldPrice = 0;
    static int oldInvQty = 0;
    static int odlStkQty = 0;
    static String supplierName = "";
    
    
    /**
     * Creates new form Edit
     */
    public Edit() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        searchField = new javax.swing.JTextField();
        Search_OK = new javax.swing.JButton();
        Fill = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        ProductTable2 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        supplier = new javax.swing.JTextField();
        StkQty = new javax.swing.JTextField();
        Price = new javax.swing.JTextField();
        Cost = new javax.swing.JTextField();
        Desc = new javax.swing.JTextField();
        InvQty = new javax.swing.JTextField();
        DecreaseQTY = new javax.swing.JButton();
        DecreaseQTY1 = new javax.swing.JButton();
        IncreaseQTY = new javax.swing.JButton();
        IncreaseQTY1 = new javax.swing.JButton();
        remove = new javax.swing.JButton();
        saveChanges = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));
        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setPreferredSize((new java.awt.Dimension(scrnSize.width -150, scrnSize.height - taskBarHeight)));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setPreferredSize(new java.awt.Dimension(962, 50));

        jLabel1.setText("SEARCH");

        searchField.setPreferredSize(new java.awt.Dimension(300, 30));
        searchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFieldActionPerformed(evt);
            }
        });

        Search_OK.setBackground(new java.awt.Color(51, 51, 255));
        Search_OK.setText("OK");
        Search_OK.setPreferredSize(new java.awt.Dimension(80, 30));
        Search_OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_OKActionPerformed(evt);
            }
        });

        Fill.setBackground(new java.awt.Color(51, 51, 255));
        Fill.setText("FILL");
        Fill.setPreferredSize(new java.awt.Dimension(80, 30));
        Fill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FillActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Search_OK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Fill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Search_OK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Fill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        ProductTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PRODUCT", "PRICE (R)", "INV QTY", "STK QTY", "SUPPLIER"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ProductTable2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ProductTable2.setRowHeight(30);
        ProductTable2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ProductTable2.setShowGrid(true);
        ProductTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductTable2MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(ProductTable2);
        if (ProductTable2.getColumnModel().getColumnCount() > 0) {
            ProductTable2.getColumnModel().getColumn(0).setPreferredWidth(500);
            ProductTable2.getColumnModel().getColumn(1).setPreferredWidth(30);
            ProductTable2.getColumnModel().getColumn(2).setPreferredWidth(30);
            ProductTable2.getColumnModel().getColumn(3).setPreferredWidth(30);
            ProductTable2.getColumnModel().getColumn(4).setPreferredWidth(40);
        }

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setPreferredSize(new java.awt.Dimension(200, 50));

        jLabel2.setText("INV QTY");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 75, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(0, 76, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 15, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(0, 15, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setPreferredSize(new java.awt.Dimension(200, 50));

        jLabel3.setText("SUPPLIER ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 196, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setPreferredSize(new java.awt.Dimension(200, 50));

        jLabel4.setText("STK QTY");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 196, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setPreferredSize(new java.awt.Dimension(200, 50));

        jLabel5.setText("SELLING PRICE");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 196, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel6.setBackground(new java.awt.Color(153, 153, 153));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.setPreferredSize(new java.awt.Dimension(200, 50));

        jLabel6.setText("COST");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 196, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel7.setBackground(new java.awt.Color(153, 153, 153));
        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.setPreferredSize(new java.awt.Dimension(200, 50));

        jLabel7.setText("PRODUCT DESCRIPTION");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 196, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel7)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 46, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel7)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        supplier.setText(" ");
        supplier.setPreferredSize(new java.awt.Dimension(300, 30));

        StkQty.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        StkQty.setPreferredSize(new java.awt.Dimension(40, 30));

        Price.setText(" ");
        Price.setPreferredSize(new java.awt.Dimension(300, 30));

        Cost.setText(" ");
        Cost.setPreferredSize(new java.awt.Dimension(300, 30));

        Desc.setText(" ");
        Desc.setPreferredSize(new java.awt.Dimension(600, 30));

        InvQty.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        InvQty.setText(" ");
        InvQty.setPreferredSize(new java.awt.Dimension(40, 30));

        DecreaseQTY.setBackground(new java.awt.Color(204, 0, 0));
        DecreaseQTY.setText("-");
        DecreaseQTY.setPreferredSize(new java.awt.Dimension(30, 30));
        DecreaseQTY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DecreaseQTYActionPerformed(evt);
            }
        });

        DecreaseQTY1.setBackground(new java.awt.Color(204, 0, 0));
        DecreaseQTY1.setText("-");
        DecreaseQTY1.setPreferredSize(new java.awt.Dimension(30, 30));
        DecreaseQTY1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DecreaseQTY1ActionPerformed(evt);
            }
        });

        IncreaseQTY.setBackground(new java.awt.Color(51, 153, 0));
        IncreaseQTY.setText("+");
        IncreaseQTY.setPreferredSize(new java.awt.Dimension(30, 30));
        IncreaseQTY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IncreaseQTYActionPerformed(evt);
            }
        });

        IncreaseQTY1.setBackground(new java.awt.Color(51, 153, 0));
        IncreaseQTY1.setText("+");
        IncreaseQTY1.setPreferredSize(new java.awt.Dimension(30, 30));
        IncreaseQTY1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IncreaseQTY1ActionPerformed(evt);
            }
        });

        remove.setBackground(new java.awt.Color(204, 102, 0));
        remove.setText("REMOVE");
        remove.setPreferredSize(new java.awt.Dimension(150, 50));
        remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeActionPerformed(evt);
            }
        });

        saveChanges.setBackground(new java.awt.Color(0, 153, 0));
        saveChanges.setText("SAVE CHANGES");
        saveChanges.setPreferredSize(new java.awt.Dimension(150, 50));
        saveChanges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveChangesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1074, Short.MAX_VALUE)
                    .addComponent(jScrollPane4))
                .addGap(30, 30, 30))
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Desc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(supplier, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Price, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Cost, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(DecreaseQTY1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(InvQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(IncreaseQTY, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(DecreaseQTY, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(StkQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(IncreaseQTY1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 235, Short.MAX_VALUE)
                                .addComponent(remove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(85, 85, 85))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(876, Short.MAX_VALUE)
                    .addComponent(saveChanges, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(84, 84, 84)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Desc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(Cost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(Price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(InvQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DecreaseQTY1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IncreaseQTY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(StkQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DecreaseQTY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IncreaseQTY1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(remove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(supplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(533, Short.MAX_VALUE)
                    .addComponent(saveChanges, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(30, 30, 30)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchFieldActionPerformed

    private void Search_OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_OKActionPerformed
        // TODO add your handling code here:
        // searching for product and adding to table

        int rowIndex = 0;

        DefaultTableModel searchTable = (DefaultTableModel)ProductTable2.getModel();
        searchTable.setRowCount(0);
        for (int i = 0; i < products.size(); i ++){
            if (((RMPSPOS_ProductData) products.get(i)).getProdDescription().contains(searchField.getText()))
            {
                String [] searchTableResults = {
                    ((RMPSPOS_ProductData)products.get(i)).getProdDescription(),
                    String.valueOf(((RMPSPOS_ProductData)products.get(i)).getPrice()),
                    String.valueOf(((RMPSPOS_ProductData)products.get(i)).getInventoryQty()),
                    String.valueOf(((RMPSPOS_ProductData)products.get(i)).getStockQty()),
                    String.valueOf(((RMPSPOS_ProductData)products.get(i)).getSupplier())};

                searchTable.insertRow(rowIndex, searchTableResults);
                rowIndex ++;

            }
        } 
    
    }//GEN-LAST:event_Search_OKActionPerformed

    private void FillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FillActionPerformed
        // TODO add your handling code here:
        DefaultTableModel searchTable = (DefaultTableModel)ProductTable2.getModel();
        searchTable.setRowCount(0);
        int rowIndex = 0;

        for (int i = 0; i < products.size(); i ++){
            String [] inventoryTableResults = {
                ((RMPSPOS_ProductData)products.get(i)).getProdDescription(),
                    String.valueOf(((RMPSPOS_ProductData)products.get(i)).getPrice()),
                    String.valueOf(((RMPSPOS_ProductData)products.get(i)).getInventoryQty()),
                    String.valueOf(((RMPSPOS_ProductData)products.get(i)).getStockQty()),
                    String.valueOf(((RMPSPOS_ProductData)products.get(i)).getSupplier())};
            searchTable.insertRow(rowIndex, inventoryTableResults);
            rowIndex ++;
        }
    }//GEN-LAST:event_FillActionPerformed

    private void ProductTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductTable2MouseClicked
        // TODO add your handling code here:
        
        JTable source = (JTable)evt.getSource();
        int row = source.rowAtPoint( evt.getPoint() );
        String prodDescCodeInRow = source.getModel().getValueAt(row, 0 )+"";

        for ( int i = 0; i < products.size(); i ++){
            if (((RMPSPOS_ProductData) products.get(i)).getProdDescription().equals(prodDescCodeInRow)){
                Desc.setText(((RMPSPOS_ProductData) products.get(i)).getProdDescription());
                Price.setText(String.valueOf(((RMPSPOS_ProductData) products.get(i)).getPrice()));
                Cost.setText(String.valueOf(((RMPSPOS_ProductData) products.get(i)).getCostPrice()));
                InvQty.setText(String.valueOf(((RMPSPOS_ProductData) products.get(i)).getInventoryQty()));
                StkQty.setText(String.valueOf(((RMPSPOS_ProductData) products.get(i)).getStockQty()));
                supplier.setText(((RMPSPOS_ProductData) products.get(i)).getSupplier());
                
                oldDesc = ((RMPSPOS_ProductData)products.get(i)).getProdDescription();
                oldCost = ((RMPSPOS_ProductData)products.get(i)).getPrice();
                oldPrice = ((RMPSPOS_ProductData)products.get(i)).getPrice();
                oldInvQty = ((RMPSPOS_ProductData)products.get(i)).getInventoryQty();
                odlStkQty = ((RMPSPOS_ProductData)products.get(i)).getStockQty();
                supplierName = ((RMPSPOS_ProductData)products.get(i)).getSupplier();
            }
        }
        
        
        
    }//GEN-LAST:event_ProductTable2MouseClicked

    private void DecreaseQTYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DecreaseQTYActionPerformed
        // TODO add your handling code here:

        int currentQty = Integer.parseInt(StkQty.getText());
        int newQty = currentQty - 1;
        StkQty.setText(String.valueOf(newQty));
    }//GEN-LAST:event_DecreaseQTYActionPerformed

    private void DecreaseQTY1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DecreaseQTY1ActionPerformed
        // TODO add your handling code here:
        int currentQty = Integer.parseInt(StkQty.getText());
        int newQty = currentQty - 1;
        StkQty.setText(String.valueOf(newQty));
    }//GEN-LAST:event_DecreaseQTY1ActionPerformed

    private void IncreaseQTYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IncreaseQTYActionPerformed
        // TODO add your handling code here:
        int currentQty = Integer.parseInt(InvQty.getText());
        int newQty = currentQty + 1;
        InvQty.setText(String.valueOf(newQty));
    }//GEN-LAST:event_IncreaseQTYActionPerformed

    private void IncreaseQTY1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IncreaseQTY1ActionPerformed
        // TODO add your handling code here:
        int currentQty = Integer.parseInt(StkQty.getText());
        int newQty = currentQty + 1;
        StkQty.setText(String.valueOf(newQty));
    }//GEN-LAST:event_IncreaseQTY1ActionPerformed

    private void saveChangesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveChangesActionPerformed
        // TODO add your handling code here:
        if (Desc.getText().isBlank() || Cost.getText().isBlank() || Price.getText().isBlank() ||
                InvQty.getText().isBlank() || StkQty.getText().isBlank() || supplier.getText().isBlank()){
            
            JFrame frame = new JFrame();
            JOptionPane.showMessageDialog(frame, "CHECK INPUT");
        }
        else{
            
            String productDescription = Desc.getText();
            int newQty = Integer.parseInt(InvQty.getText());
            int newStock = Integer.parseInt(StkQty.getText());
            String newCost = Cost.getText();
            String newSellingPrice = Price.getText();
            String newSupplierName = supplier.getText();

            for (int i = 0; i < products.size(); i ++){
                if (((RMPSPOS_ProductData) products.get(i)).getProdDescription().equals(oldDesc)){
                    ((RMPSPOS_ProductData) products.get(i)).setProdDescription(productDescription);
                    ((RMPSPOS_ProductData) products.get(i)).setStockQty(newStock);
                    ((RMPSPOS_ProductData) products.get(i)).setCostPrice(Float.parseFloat(newCost));
                    ((RMPSPOS_ProductData) products.get(i)).setPrice(Float.parseFloat(newSellingPrice));
                    ((RMPSPOS_ProductData) products.get(i)).setInventoryQty(newQty);
                    ((RMPSPOS_ProductData) products.get(i)).setSupplier(newSupplierName);
                }
            }

            DefaultTableModel searchTable = (DefaultTableModel)ProductTable2.getModel();

            searchTable.setRowCount(0);
            Desc.setText("");
            InvQty.setText("");
            Cost.setText("");
            Price.setText("");
            supplier.setText("");
            StkQty.setText("");

            JFrame frame = new JFrame();

            JOptionPane.showMessageDialog(frame, "ACTION COMPLETE");

            try {
                    SavingChangesToFile();
                } 
            catch (IOException ex) {
                    Logger.getLogger(Add.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_saveChangesActionPerformed

    private void removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeActionPerformed
        // TODO add your handling code here:

        for (int a = 0; a < products.size(); a ++){
            if (oldDesc.equals(((RMPSPOS_ProductData) products.get(a)).getProdDescription())){
                 products.remove(a);
            }
        }
        DefaultTableModel searchTable = (DefaultTableModel)ProductTable2.getModel();
        searchTable.setRowCount(0);
        Desc.setText("");
        InvQty.setText("");
        Cost.setText("");
        Price.setText("");
        supplier.setText("");
        StkQty.setText("");
        
        JFrame frame = new JFrame();
        JOptionPane.showMessageDialog(frame, "ITEM REMOVED"
                  ); 
        try {
            SavingChangesToFile();
        } catch (IOException ex) {
            Logger.getLogger(Edit.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_removeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Cost;
    private javax.swing.JButton DecreaseQTY;
    private javax.swing.JButton DecreaseQTY1;
    private javax.swing.JTextField Desc;
    private javax.swing.JButton Fill;
    private javax.swing.JButton IncreaseQTY;
    private javax.swing.JButton IncreaseQTY1;
    private javax.swing.JTextField InvQty;
    private javax.swing.JTextField Price;
    private javax.swing.JTable ProductTable2;
    private javax.swing.JButton Search_OK;
    private javax.swing.JTextField StkQty;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton remove;
    private javax.swing.JButton saveChanges;
    private javax.swing.JTextField searchField;
    private javax.swing.JTextField supplier;
    // End of variables declaration//GEN-END:variables
}
